### ISSUE TITLE
fails to build with hoauth2 1.3.0

### ISSUE THREAD

**Issue by LocutusOfBorg** [jgm/gitit#607]
Hello, seems that gitit needs patches for the new hoauth2
https://launchpad.net/~costamagnagianfranco/+archive/ubuntu/locutusofborg-ppa/+build/13712897

```
[19 of 22] Compiling Network.Gitit.Authentication.Github ( src/Network/Gitit/Authentication/Github.hs, dist-ghc/build/Network/Gitit/Authentication/Github.o )

src/Network/Gitit/Authentication/Github.hs:104:43: error:
    • Expecting one more argument to ‘OAuth2Result GithubUser’
      Expected a type, but ‘OAuth2Result GithubUser’ has kind ‘* -> *’
    • In the first argument of ‘IO’, namely ‘OAuth2Result GithubUser’
      In the type signature:
        userInfo :: Manager -> AccessToken -> IO (OAuth2Result GithubUser)

src/Network/Gitit/Authentication/Github.hs:107:43: error:
    • Expecting one more argument to ‘OAuth2Result [GithubUserMail]’
      Expected a type, but
      ‘OAuth2Result [GithubUserMail]’ has kind
      ‘* -> *’
    • In the first argument of ‘IO’, namely
        ‘OAuth2Result [GithubUserMail]’
      In the type signature:
        mailInfo :: Manager
                    -> AccessToken -> IO (OAuth2Result [GithubUserMail])

src/Network/Gitit/Authentication/Github.hs:110:59: error:
    • Expecting one more argument to ‘OAuth2Result BSL.ByteString’
      Expected a type, but
      ‘OAuth2Result BSL.ByteString’ has kind
      ‘* -> *’
    • In the first argument of ‘IO’, namely
        ‘OAuth2Result BSL.ByteString’
      In the type signature:
        orgInfo :: Text
                   -> Text
                      -> Manager -> AccessToken -> IO (OAuth2Result BSL.ByteString)
/usr/share/cdbs/1/class/hlibrary.mk:147: recipe for target 'build-ghc-stamp' failed
make: *** [build-ghc-stamp] Error 1

```
